imports:
  - { resource: commandBusServices.yml }

services:
  user.user_provider.email:
    class: Sokil\UserBundle\Security\UserProvider\EmailUserProvider
    arguments:
      - '@user.repository.user'

  user.voter:
    class: Sokil\UserBundle\Voter\UserVoter
    arguments:
      - '@security.access.role_hierarchy_voter'
    tags:
       - { name: security.voter }

  user.authentication_success_handler:
    class: Sokil\UserBundle\EventListener\AuthenticationSuccessHandler
    arguments: ['@security.http_utils', {}]

  user.authentication_failure_handler:
    class: Sokil\UserBundle\EventListener\AuthenticationFailureHandler
    arguments: ['@http_kernel', '@security.http_utils', {}, "@logger"]

  user.logout_success_handler:
    class: Sokil\UserBundle\EventListener\LogoutSuccessHandler
    arguments: ['@security.http_utils', '/']

  user.validation_errors_converter:
    class: Sokil\UserBundle\Converter\ValidationErrorsConverter

  user.repository.user_attributes:
    class: Sokil\UserBundle\Repository\UserAttributeRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - 'UserBundle:UserAttribute'

  user.repository.user:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - 'UserBundle:User'

  user.form.type.user_attribute.entity:
    class: Sokil\UserBundle\Form\Type\UserAttribute\EntityFormType
    tags:
      - {name: form.type}

  user.form.type.user_attribute.string:
    class: Sokil\UserBundle\Form\Type\UserAttribute\StringFormType

  user.user_normalizer:
    class: Sokil\UserBundle\Serializer\Normalizer\UserNormalizer
    arguments:
      - '@security.authorization_checker'
      - '@doctrine'
      - '@translator'

  user.user_attribute_normalizer:
    class: Sokil\UserBundle\Serializer\Normalizer\UserAttributeNormalizer

  user.serializer.normalizer.role_group:
    class: Sokil\UserBundle\Serializer\Normalizer\RoleGroupNormalizer

  user.converter.entity_discriminator_map:
    class: Sokil\UserBundle\Converter\DiscriminatorMapConverter
    arguments:
      - '@doctrine'
      - '@translator'
