services:
    user.voter:
        class: Sokil\UserBundle\Voter\UserVoter
        arguments:
          - '@security.access.role_hierarchy_voter'
        tags:
           - { name: security.voter }

    user.authentication_success_handler:
        class: Sokil\UserBundle\EventListener\AuthenticationSuccessHandler
        arguments: ['@security.http_utils', {}]

    user.authentication_failure_handler:
        class: Sokil\UserBundle\EventListener\AuthenticationFailureHandler
        arguments: ['@http_kernel', '@security.http_utils', {}, "@logger"]

    user.validation_errors_converter:
        class: Sokil\Converter\ValidationErrorsConverter

    user.registration_form:
        class: Sokil\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - {name: form.type, alias: user_registration_form}

    user.user_edit_form_handler:
        class: Sokil\UserBundle\Form\Handler\UserEditFormHandler
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@fos_user.user_manager'
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@validator'

    user.repository.user_attributes:
        class: Sokil\UserBundle\Repository\UserAttributeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - 'UserBundle:UserAttribute'

    user.user_normalizer:
        class: Sokil\UserBundle\Serializer\Normalizer\UserNormalizer
        arguments:
            - '@security.authorization_checker'
            - '@doctrine'
            - '@translator'

    user.user_attribute_normalizer:
        class: Sokil\UserBundle\Serializer\Normalizer\UserAttributeNormalizer

    user.serializer.normalizer.role_group:
        class: Sokil\UserBundle\Serializer\Normalizer\RoleGroupNormalizer

    user.converter.entity_discriminator_map:
        class: Sokil\UserBundle\Converter\DiscriminatorMapConverter
        arguments:
            - '@doctrine'
            - '@translator'