Sokil\UserBundle\Entity\User:
    properties:
        name:
            - NotBlank: {}
        email:
            - NotBlank: {}
            - Email: {checkMX: false}
        plainPassword:
            - NotBlank: {groups: [Registration]}